apiVersion: v1
kind: Service
metadata:
  name: backendapi
spec:
  type: LoadBalancer
  selector:
    app: backendapi
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

#To get public ip on aks use "type: LoadBalancer" and for private IP "type: ClusterIP"